services:
  redis:
    image: redis:latest
    container_name: neura-redis
    ports:
      - "6380:6379"
    networks:
      - app-network
  postgresql:
    image: postgres:16.9
    container_name: neura-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: OhJuILyCLmPqzTjwZmxRHvTMmCWISkPv
      POSTGRES_DB: neura
    ports:
      - "5435:5432"
    networks:
      - app-network
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:

networks:
  app-network:
    driver: bridge